<?php

/**
* Implements hook_block_info().
*/
function reg_block_block_info() {
  $blocks['registration_block'] = array(
    'info' => t('Register'),
    'cache' => DRUPAL_CACHE_PER_ROLE, // default
    'status' => TRUE, 
    'region' => 'content', // Not usually provided. 
    'visibility' => BLOCK_VISIBILITY_LISTED, // Not usually provided. 
    'pages' => '<front>', // Not usually provided here.
  );

  return $blocks;
}

/**
* Implements hook_block_view().
*/
function reg_block_block_view($delta = '') {
  //The $delta parameter tells us which block is being requested.
  switch ($delta) {
    case 'registration_block':
      global $user;
      if (empty($user) || !$user->uid > 1) {
	$block['subject'] = t('Register');
	$block['content'] = drupal_render(drupal_get_form('user_register_form'));
      }
     break;
  }
  return $block;
}
